<a href="https://colab.research.google.com/github/soltiste/ii-in-economi/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Загрузите выборку из файла titanic.csv с помощью пакета Pandas.
2. Оставьте в выборке четыре признака: класс пассажира (Pclass), цену билета (Fare), возраст пассажира (Age) и его пол (Sex).
3. Обратите внимание, что признак Sex имеет строковые значения.
4. Выделите целевую переменную — она записана в столбце Survived.
5. В данных есть пропущенные значения — например, для некоторых
пассажиров неизвестен их возраст. Такие записи при чтении их в
pandas принимают значение nan. Найдите все объекты, у которых
есть пропущенные признаки, и удалите их из выборки.
6. Обучите решающее дерево с параметром random_state=241 и остальными параметрами по умолчанию.
7. Вычислите важности признаков и найдите два признака с наибольшей важностью. Их названия будут ответами для данной задачи
(в качестве ответа укажите названия признаков через запятую без
пробелов).

In [4]:
import pandas as pd
import numpy as np
from scipy. stats import pearsonr
from sklearn.tree import DecisionTreeClassifier


data = pd.read_csv('/content/drive/MyDrive/titanic.csv',
                   index_col='PassengerId')

In [5]:
data.head(10)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [11]:
df = data[['Pclass', 'Fare', 'Age', 'Sex', 'Survived']].dropna()
df['Sex'].loc[df['Sex'] == 'female'] = 1
df['Sex'].loc[df['Sex'] == 'male'] = 0
df

<ipython-input-11-afdace044fa2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'].loc[df['Sex'] == 'male'] = 0

             Pclass     Fare   Age Sex  Survived
PassengerId
1                 3   7.2500  22.0   0         0
2                 1  71.2833  38.0   1         1
3                 3   7.9250  26.0   1         1
4                 1  53.1000  35.0   1         1
5                 3   8.0500  35.0   0         0
...             ...      ...   ...  ..       ...
886               3  29.1250  39.0   1         0
887               2  13.0000  27.0   0         0
888               1  30.0000  19.0   1         1
890               1  30.0000  26.0   0         1
891               3   7.7500  32.0   0         0

[714 rows x 5 columns]

In [13]:
clf = DecisionTreeClassifier(random_state=241)
clf.fit(df[['Pclass', 'Fare', 'Age', 'Sex']], df[['Survived']])

DecisionTreeClassifier(random_state=241)

In [17]:
important = pd.Series(clf.feature_importances_,
                      index=list(df[['Pclass', 'Fare', 'Age', 'Sex']]))
print(' '.join(important.sort_values(ascending=False).head(2).index.values))

Sex Fare